version: "2"

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/db-data

  app:
    # vvv command is to remove old server.pid before starting server again
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    build: .
    environment:
      - PGHOST=db
      - PGUSER=postgres
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db