---
openapi: 3.0.1
info:
  title: API V1.0
  version: v1.0
components:
  schemas:
    errors_object:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
      required:
      - errors
    money_send_transaction_response:
      type: object
      properties:
        id:
          type: integer
          format: int64
        amount:
          type: number
          format: double
        sender_id:
          type: integer
          format: int64
        receiver_id:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - amount
      - sender_id
      - receiver_id
      - created_at
      - updated_at
    money_send_transaction_request:
      type: object
      properties:
        amount:
          type: number
          format: double
        sender_id:
          type: integer
          format: int64
        receiver_id:
          type: integer
          format: int64
      required:
      - amount
      - sender_id
      - receiver_id
paths:
  "/money_send_transaction":
    post:
      summary: Creates a transaction
      tags:
      - MoneySendTransaction
      parameters: []
      responses:
        '201':
          description: Transaction created
          content:
            application/json:
              example:
                id: 1
                amount: '3.01'
                status: succeeded
                created_at: '2020-01-01T00:00:00.000Z'
                updated_at: '2020-01-01T00:00:00.000Z'
                sender_id: 1
                receiver_id: 2
        '422':
          description: Invalid request
          content:
            application/json:
              example:
                errors:
                - Request is missing required parameters. Please check OpenAPI spec
                  and check if it mathces. Contact support if this error presist despite
                  matching OpenAPI spec.
        '403':
          description: 'Forbidden: Account pending or unverified'
          content:
            application/json:
              example:
                errors:
                - Unverified and pending accounts cannot send or receive transacctions.
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/money_send_transaction_request"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
