default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: postgres # Replace this with <%= ENV['DATABASE_USERNAME'] %> in actual development
  password: password # Replace this with <%= ENV['DATABASE_PASSWORD'] %> in actual development

development:
  <<: *default
  database: public-interviews-backend_development

test:
  <<: *default
  database: public-interviews-backend_test
